version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8011:80"
    links:
      - bis

  bis:
    build:
      context: ./
      dockerfile: bis.dockerfile
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  
  database:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: bisapi
    ports:
        - "33061:3306"

  cache:
    image: redis:3.0
    ports:
      - "63791:6379"
